/*
 * Created on 26 Feb 2017 ( Time 16:22:34 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package net.kumasi.debtmonkeys.service.domain.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "Payment_History"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="Payment_History", catalog="debtmonkey" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="PaymentHistoryEntity.countAll", query="SELECT COUNT(x) FROM PaymentHistoryEntity x" ),
  @NamedQuery ( name="PaymentHistoryEntity.byAccountId", query="SELECT h FROM PaymentHistoryEntity h where h.account.id = :accountId" )
} )
public class PaymentHistoryEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="idPayment_History", nullable=false)
    private Integer    idpaymentHistory ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="balance_remaining")
    private Double     balanceRemaining ;

    @Column(name="amount_paid", nullable=false)
    private Double     amountPaid   ;

    @Temporal(TemporalType.DATE)
    @Column(name="payment_date", nullable=false)
    private Date       paymentDate  ;

    @Temporal(TemporalType.DATE)
    @Column(name="next_payment_date")
    private Date       nextPaymentDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_modified")
    private Date       dateModified ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_created")
    private Date       dateCreated  ;

	// "accountId" (column "Account_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="Account_id", referencedColumnName="id")
    private AccountEntity account     ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public PaymentHistoryEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdpaymentHistory( Integer idpaymentHistory ) {
        this.idpaymentHistory = idpaymentHistory ;
    }
    public Integer getIdpaymentHistory() {
        return this.idpaymentHistory;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : balance_remaining ( DOUBLE ) 
    public void setBalanceRemaining( Double balanceRemaining ) {
        this.balanceRemaining = balanceRemaining;
    }
    public Double getBalanceRemaining() {
        return this.balanceRemaining;
    }

    //--- DATABASE MAPPING : amount_paid ( DOUBLE ) 
    public void setAmountPaid( Double amountPaid ) {
        this.amountPaid = amountPaid;
    }
    public Double getAmountPaid() {
        return this.amountPaid;
    }

    //--- DATABASE MAPPING : payment_date ( DATE ) 
    public void setPaymentDate( Date paymentDate ) {
        this.paymentDate = paymentDate;
    }
    public Date getPaymentDate() {
        return this.paymentDate;
    }

    //--- DATABASE MAPPING : next_payment_date ( DATE ) 
    public void setNextPaymentDate( Date nextPaymentDate ) {
        this.nextPaymentDate = nextPaymentDate;
    }
    public Date getNextPaymentDate() {
        return this.nextPaymentDate;
    }

    //--- DATABASE MAPPING : date_modified ( DATETIME ) 
    public void setDateModified( Date dateModified ) {
        this.dateModified = dateModified;
    }
    public Date getDateModified() {
        return this.dateModified;
    }

    //--- DATABASE MAPPING : date_created ( DATETIME ) 
    public void setDateCreated( Date dateCreated ) {
        this.dateCreated = dateCreated;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setAccount( AccountEntity account ) {
        this.account = account;
    }
    public AccountEntity getAccount() {
        return this.account;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(idpaymentHistory);
        sb.append("]:"); 
        sb.append(balanceRemaining);
        sb.append("|");
        sb.append(amountPaid);
        sb.append("|");
        sb.append(paymentDate);
        sb.append("|");
        sb.append(nextPaymentDate);
        sb.append("|");
        sb.append(dateModified);
        sb.append("|");
        sb.append(dateCreated);
        return sb.toString(); 
    } 

}
