
/*
 * Created on 26 Feb 2017 ( Time 16:22:34 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.debtmonkeys.service.mock;

import java.util.LinkedList;
import java.util.List;

import net.kumasi.debtmonkeys.service.domain.jpa.AccountOwnerEntity;
import net.kumasi.debtmonkeys.service.mock.tool.MockValues;

public class AccountOwnerEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public AccountOwnerEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public AccountOwnerEntity createInstance( Integer id ) {
		AccountOwnerEntity entity = new AccountOwnerEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setUserName( mockValues.nextString(15) ) ; // java.lang.String 
		entity.setPassword( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setEmailAddress( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setFirstName( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setLastName( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setNetMonthlyIncome( mockValues.nextDouble() ) ; // java.lang.Double 
		entity.setIsadmin( mockValues.nextString(1) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setListOfAccount( TODO ) ; // List<Account> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<AccountOwnerEntity> createList(int count) {
		List<AccountOwnerEntity> list = new LinkedList<AccountOwnerEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
