/*
 * Created on 26 Feb 2017 ( Time 16:22:54 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.debtmonkeys.service.business.service;

import java.util.List;

import net.kumasi.debtmonkeys.service.domain.Account;

/**
 * Business Service Interface for entity Account.
 */
public interface AccountService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Account findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Account> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Account save(Account entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Account update(Account entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Account create(Account entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
