/*
 * Created on 26 Feb 2017 ( Time 16:22:54 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.debtmonkeys.service.domain;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class PaymentHistory implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer idpaymentHistory;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    private Double balanceRemaining;

    @NotNull
    private Double amountPaid;

    @NotNull
    private Date paymentDate;


    private Date nextPaymentDate;


    private Date dateModified;


    private Date dateCreated;

    @NotNull
    private Integer accountId;
    
    private Account account;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdpaymentHistory( Integer idpaymentHistory ) {
        this.idpaymentHistory = idpaymentHistory ;
    }

    public Integer getIdpaymentHistory() {
        return this.idpaymentHistory;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setBalanceRemaining( Double balanceRemaining ) {
        this.balanceRemaining = balanceRemaining;
    }
    public Double getBalanceRemaining() {
        return this.balanceRemaining;
    }

    public void setAmountPaid( Double amountPaid ) {
        this.amountPaid = amountPaid;
    }
    public Double getAmountPaid() {
        return this.amountPaid;
    }

    public void setPaymentDate( Date paymentDate ) {
        this.paymentDate = paymentDate;
    }
    public Date getPaymentDate() {
        return this.paymentDate;
    }

    public void setNextPaymentDate( Date nextPaymentDate ) {
        this.nextPaymentDate = nextPaymentDate;
    }
    public Date getNextPaymentDate() {
        return this.nextPaymentDate;
    }

    public void setDateModified( Date dateModified ) {
        this.dateModified = dateModified;
    }
    public Date getDateModified() {
        return this.dateModified;
    }

    public void setDateCreated( Date dateCreated ) {
        this.dateCreated = dateCreated;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }

    public void setAccountId( Integer accountId ) {
        this.accountId = accountId;
    }
    public Integer getAccountId() {
        return this.accountId;
    }

    

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public Account getAccount() {
		return account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

		public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idpaymentHistory);
        sb.append("|");
        sb.append(balanceRemaining);
        sb.append("|");
        sb.append(amountPaid);
        sb.append("|");
        sb.append(paymentDate);
        sb.append("|");
        sb.append(nextPaymentDate);
        sb.append("|");
        sb.append(dateModified);
        sb.append("|");
        sb.append(dateCreated);
        sb.append("|");
        sb.append(accountId);
        return sb.toString(); 
    } 


}
