/*
 * Created on 26 Feb 2017 ( Time 16:22:54 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.debtmonkeys.service.web.listitem;

import net.kumasi.debtmonkeys.service.domain.PaymentHistory;
import net.kumasi.debtmonkeys.service.web.common.ListItem;

public class PaymentHistoryListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public PaymentHistoryListItem(PaymentHistory paymentHistory) {
		super();

		this.value = ""
			 + paymentHistory.getIdpaymentHistory()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = paymentHistory.getPaymentDate().toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
