/*
 * Created on 26 Feb 2017 ( Time 16:22:34 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package net.kumasi.debtmonkeys.service.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import net.kumasi.debtmonkeys.service.domain.jpa.AccountOwnerEntity;
import net.kumasi.debtmonkeys.service.persistence.commons.jpa.GenericJpaService;
import net.kumasi.debtmonkeys.service.persistence.commons.jpa.JpaOperation;
import net.kumasi.debtmonkeys.service.persistence.services.AccountOwnerPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "AccountOwner" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class AccountOwnerPersistenceJPA extends GenericJpaService<AccountOwnerEntity, Integer> implements AccountOwnerPersistence {

	/**
	 * Constructor
	 */
	public AccountOwnerPersistenceJPA() {
		super(AccountOwnerEntity.class);
	}

	@Override
	public AccountOwnerEntity load( Integer id ) {
		return super.load( id );
	}

	@Override
	public boolean delete( Integer id ) {
		return super.delete( id );
	}

	@Override
	public boolean delete(AccountOwnerEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getId() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("AccountOwnerEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
