/*
 * Created on 26 Feb 2017 ( Time 16:22:34 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package net.kumasi.debtmonkeys.service.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import net.kumasi.debtmonkeys.service.domain.jpa.PaymentHistoryEntity;
import net.kumasi.debtmonkeys.service.persistence.commons.jpa.GenericJpaService;
import net.kumasi.debtmonkeys.service.persistence.commons.jpa.JpaOperation;
import net.kumasi.debtmonkeys.service.persistence.services.PaymentHistoryPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "PaymentHistory" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class PaymentHistoryPersistenceJPA extends GenericJpaService<PaymentHistoryEntity, Integer> implements PaymentHistoryPersistence {

	/**
	 * Constructor
	 */
	public PaymentHistoryPersistenceJPA() {
		super(PaymentHistoryEntity.class);
	}

	@Override
	public PaymentHistoryEntity load( Integer idpaymentHistory ) {
		return super.load( idpaymentHistory );
	}

	@Override
	public boolean delete( Integer idpaymentHistory ) {
		return super.delete( idpaymentHistory );
	}

	@Override
	public boolean delete(PaymentHistoryEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getIdpaymentHistory() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("PaymentHistoryEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
