/*
 * Created on 26 Feb 2017 ( Time 16:22:54 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.debtmonkeys.service.web.common;

public interface ListItem {

	public String getValue();
	
	public String getLabel();
}
