/*
 * Created on 26 Feb 2017 ( Time 16:22:45 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.debtmonkeys.service.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import net.kumasi.debtmonkeys.service.domain.AccountType;
import net.kumasi.debtmonkeys.service.domain.jpa.AccountTypeEntity;
import net.kumasi.debtmonkeys.service.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class AccountTypeServiceMapperTest {

	private AccountTypeServiceMapper accountTypeServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		accountTypeServiceMapper = new AccountTypeServiceMapper();
		accountTypeServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'AccountTypeEntity' to 'AccountType'
	 * @param accountTypeEntity
	 */
	@Test
	public void testMapAccountTypeEntityToAccountType() {
		// Given
		AccountTypeEntity accountTypeEntity = new AccountTypeEntity();
		accountTypeEntity.setAccountCode(mockValues.nextString(6));
		accountTypeEntity.setAccountName(mockValues.nextString(45));
		
		// When
		AccountType accountType = accountTypeServiceMapper.mapAccountTypeEntityToAccountType(accountTypeEntity);
		
		// Then
		assertEquals(accountTypeEntity.getAccountCode(), accountType.getAccountCode());
		assertEquals(accountTypeEntity.getAccountName(), accountType.getAccountName());
	}
	
	/**
	 * Test : Mapping from 'AccountType' to 'AccountTypeEntity'
	 */
	@Test
	public void testMapAccountTypeToAccountTypeEntity() {
		// Given
		AccountType accountType = new AccountType();
		accountType.setAccountCode(mockValues.nextString(6));
		accountType.setAccountName(mockValues.nextString(45));

		AccountTypeEntity accountTypeEntity = new AccountTypeEntity();
		
		// When
		accountTypeServiceMapper.mapAccountTypeToAccountTypeEntity(accountType, accountTypeEntity);
		
		// Then
		assertEquals(accountType.getAccountCode(), accountTypeEntity.getAccountCode());
		assertEquals(accountType.getAccountName(), accountTypeEntity.getAccountName());
	}

}