/*
 * Created on 26 Feb 2017 ( Time 16:22:45 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.debtmonkeys.service.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import net.kumasi.debtmonkeys.service.domain.AccountType;
import net.kumasi.debtmonkeys.service.domain.jpa.AccountTypeEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class AccountTypeServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public AccountTypeServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'AccountTypeEntity' to 'AccountType'
	 * @param accountTypeEntity
	 */
	public AccountType mapAccountTypeEntityToAccountType(AccountTypeEntity accountTypeEntity) {
		if(accountTypeEntity == null) {
			return null;
		}

		//--- Generic mapping 
		AccountType accountType = map(accountTypeEntity, AccountType.class);

		return accountType;
	}
	
	/**
	 * Mapping from 'AccountType' to 'AccountTypeEntity'
	 * @param accountType
	 * @param accountTypeEntity
	 */
	public void mapAccountTypeToAccountTypeEntity(AccountType accountType, AccountTypeEntity accountTypeEntity) {
		if(accountType == null) {
			return;
		}

		//--- Generic mapping 
		map(accountType, accountTypeEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}