/*
 * Created on 26 Feb 2017 ( Time 16:22:45 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.debtmonkeys.service.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import net.kumasi.debtmonkeys.service.domain.AccountOwner;
import net.kumasi.debtmonkeys.service.domain.jpa.AccountOwnerEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class AccountOwnerServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public AccountOwnerServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'AccountOwnerEntity' to 'AccountOwner'
	 * @param accountOwnerEntity
	 */
	public AccountOwner mapAccountOwnerEntityToAccountOwner(AccountOwnerEntity accountOwnerEntity) {
		if(accountOwnerEntity == null) {
			return null;
		}

		//--- Generic mapping 
		AccountOwner accountOwner = map(accountOwnerEntity, AccountOwner.class);

		return accountOwner;
	}
	
	/**
	 * Mapping from 'AccountOwner' to 'AccountOwnerEntity'
	 * @param accountOwner
	 * @param accountOwnerEntity
	 */
	public void mapAccountOwnerToAccountOwnerEntity(AccountOwner accountOwner, AccountOwnerEntity accountOwnerEntity) {
		if(accountOwner == null) {
			return;
		}

		//--- Generic mapping 
		map(accountOwner, accountOwnerEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}