/*
 * Created on 26 Feb 2017 ( Time 16:22:45 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.debtmonkeys.service.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import net.kumasi.debtmonkeys.service.domain.Account;
import net.kumasi.debtmonkeys.service.domain.jpa.AccountEntity;
import net.kumasi.debtmonkeys.service.domain.jpa.AccountOwnerEntity;
import net.kumasi.debtmonkeys.service.domain.jpa.AccountTypeEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class AccountServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public AccountServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'AccountEntity' to 'Account'
	 * @param accountEntity
	 */
	public Account mapAccountEntityToAccount(AccountEntity accountEntity) {
		if(accountEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Account account = map(accountEntity, Account.class);

		//--- Link mapping ( link to AccountOwner )
		if(accountEntity.getAccountOwner() != null) {
			account.setAccountOwnerId(accountEntity.getAccountOwner().getId());
		}
		//--- Link mapping ( link to AccountType )
		if(accountEntity.getAccountType() != null) {
			account.setAccountTypeId(accountEntity.getAccountType().getId());
		}
		return account;
	}
	
	/**
	 * Mapping from 'Account' to 'AccountEntity'
	 * @param account
	 * @param accountEntity
	 */
	public void mapAccountToAccountEntity(Account account, AccountEntity accountEntity) {
		if(account == null) {
			return;
		}

		//--- Generic mapping 
		map(account, accountEntity);

		//--- Link mapping ( link : account )
		if( hasLinkToAccountOwner(account) ) {
			AccountOwnerEntity accountOwner1 = new AccountOwnerEntity();
			accountOwner1.setId( account.getAccountOwnerId() );
			accountEntity.setAccountOwner( accountOwner1 );
		} else {
			accountEntity.setAccountOwner( null );
		}

		//--- Link mapping ( link : account )
		if( hasLinkToAccountType(account) ) {
			AccountTypeEntity accountType2 = new AccountTypeEntity();
			accountType2.setId( account.getAccountTypeId() );
			accountEntity.setAccountType( accountType2 );
		} else {
			accountEntity.setAccountType( null );
		}

	}
	
	/**
	 * Verify that AccountOwner id is valid.
	 * @param AccountOwner AccountOwner
	 * @return boolean
	 */
	private boolean hasLinkToAccountOwner(Account account) {
		if(account.getAccountOwnerId() != null) {
			return true;
		}
		return false;
	}

	/**
	 * Verify that AccountType id is valid.
	 * @param AccountType AccountType
	 * @return boolean
	 */
	private boolean hasLinkToAccountType(Account account) {
		if(account.getAccountTypeId() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}