/*
 * Created on 26 Feb 2017 ( Time 16:22:54 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.debtmonkeys.service.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import net.kumasi.debtmonkeys.service.web.common.AbstractController;
import net.kumasi.debtmonkeys.service.web.common.FormMode;
import net.kumasi.debtmonkeys.service.web.common.Message;
import net.kumasi.debtmonkeys.service.web.common.MessageType;

//--- Entities
import net.kumasi.debtmonkeys.service.domain.Account;
import net.kumasi.debtmonkeys.service.domain.AccountOwner;
import net.kumasi.debtmonkeys.service.domain.AccountType;

//--- Services 
import net.kumasi.debtmonkeys.service.business.service.AccountService;
import net.kumasi.debtmonkeys.service.business.service.AccountOwnerService;
import net.kumasi.debtmonkeys.service.business.service.AccountTypeService;

//--- List Items 
import net.kumasi.debtmonkeys.service.web.listitem.AccountOwnerListItem;
import net.kumasi.debtmonkeys.service.web.listitem.AccountTypeListItem;

/**
 * Spring MVC controller for 'Account' management.
 */
@Controller
@RequestMapping("/account")
public class AccountController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "account";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "account/form";
	private static final String JSP_LIST   = "account/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/account/create";
	private static final String SAVE_ACTION_UPDATE   = "/account/update";

	//--- Main entity service
	@Resource
    private AccountService accountService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private AccountOwnerService accountOwnerService; // Injected by Spring
	@Resource
    private AccountTypeService accountTypeService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public AccountController() {
		super(AccountController.class, MAIN_ENTITY_NAME );
		log("AccountController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "AccountOwner"
	 * @param model
	 */
	private void populateListOfAccountOwnerItems(Model model) {
		List<AccountOwner> list = accountOwnerService.findAll();
		List<AccountOwnerListItem> items = new LinkedList<AccountOwnerListItem>();
		for ( AccountOwner accountOwner : list ) {
			items.add(new AccountOwnerListItem( accountOwner ) );
		}
		model.addAttribute("listOfAccountOwnerItems", items ) ;
	}

	/**
	 * Populates the combo-box "items" for the referenced entity "AccountType"
	 * @param model
	 */
	private void populateListOfAccountTypeItems(Model model) {
		List<AccountType> list = accountTypeService.findAll();
		List<AccountTypeListItem> items = new LinkedList<AccountTypeListItem>();
		for ( AccountType accountType : list ) {
			items.add(new AccountTypeListItem( accountType ) );
		}
		model.addAttribute("listOfAccountTypeItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param account
	 */
	private void populateModel(Model model, Account account, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, account);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfAccountOwnerItems(model);
			populateListOfAccountTypeItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
			populateListOfAccountTypeItems(model);
			populateListOfAccountOwnerItems(model);
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of Account found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<Account> list = accountService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new Account
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		Account account = new Account();	
		populateModel( model, account, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing Account
	 * @param model Spring MVC model
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{id}")
	public String formForUpdate(Model model, @PathVariable("id") Integer id ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		Account account = accountService.findById(id);
		populateModel( model, account, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param account  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid Account account, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				Account accountCreated = accountService.create(account); 
				model.addAttribute(MAIN_ENTITY_NAME, accountCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, account.getId() );
			} else {
				populateModel( model, account, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "account.error.create", e);
			populateModel( model, account, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param account  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid Account account, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				Account accountSaved = accountService.update(account);
				model.addAttribute(MAIN_ENTITY_NAME, accountSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, account.getId());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, account, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "account.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, account, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{id}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("id") Integer id) {
		log("Action 'delete'" );
		try {
			accountService.delete( id );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "account.error.delete", e);
		}
		return redirectToList();
	}

}
